package com.automate.enums;

public enum ConfigProperties {
  RECORD_SCREEN, START_APPIUM_SERVER,
  OVERRIDE_REPORTS, PASSED_STEP_SCREENSHOTS, FAILED_STEP_SCREENSHOTS, SKIPPED_STEP_SCREENSHOTS,
  RETRY_FAILED_TESTS, RETRY_COUNT,
  OVERRIDE_SERVER_LOG
}
